### ISSUE TITLE
Until (and after) the DAO handoff, add pointers to other ethereum clients

### ISSUE THREAD

**Issue by faraggi** [openethereum/wiki#355]
The wiki should mention the Parity ethereum spin-off somehow, and what better way to make sure the network is as equally distributed as it was when Parity was here than to promote other (smaller) clients in order to take the burden off geth?

1. I think the wiki [overview](https://wiki.parity.io/Parity-Ethereum) and the FAQ should mention the spin off process is currenly on-going.
2. Ideally, we should mention other clients as alternative such as Besu, Trinity, Nethermind, etc...

**Comment by vorot93** [comment]
DAO never happened, but @gnosispm has successfully overtaken OpenEthereum development.

Also see #365.
